### ISSUE TITLE
Migration to version 9.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/product-kitting#10]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-9.0
# Modules to migrate
- [x] bom_stock - Removed
- [x] purchase_bom_split - To be removed - By @gurneyalex - ł#14
- [x] bom_split - To be removed - By @gurneyalex - ł#14
- [x] sale_bom_split - To be removed - By @gurneyalex - ł#14

**Comment by stephankeller** [comment]
We are porting bom_stock to V8 and V9.

**Comment by pedrobaeza** [comment]
Take care, because this modules overlaps a bit with https://github.com/OCA/stock-logistics-warehouse/tree/8.0/stock_available_mrp, that it's being migrated here: https://github.com/OCA/stock-logistics-warehouse/pull/93

**Comment by stephankeller** [comment]
Sorry I missed your message
Thanks, yes we know there is some overlap.  
We need the option to be able to select the reference stock.
Also we will add a module that will allow to add the stock to the qty immediately available but with the option to activate that feature product by product.  We can contribute that as well if there is interest.

**Comment by pedrobaeza** [comment]
OK, but maybe you should talk with @clonedagain to join efforts for having only one module with all the features.

**Comment by clonedagain** [comment]
@stephankeller if by "reference stock" you mean basing the computation on something else than the virtual stock, I think it would be easy to integrate in the base stock_available module.
It also doesn't seem too complicated to make it configurable on each product.

That being said, maybe we need use something even more generic where we could make fields by combining other fields (like "A = on hand + production potential, B = virtual + quotations").
I think I read about someone already working on this idea, but I can't find a reference.

Maybe ask the PSC?

**Comment by stephankeller** [comment]
@clonedagain Sorry did not mean to ignore your message, I did not see it.
We need this for one of our customers, so we just went ahead with the porting.
I agree it should not be too hard to add in the module you are working on.
I am not sure what is the process here, this is more a decision for OCA.  BOM_stock was already there before, we are just porting it to V9.

@pedrobaeza

**Comment by clonedagain** [comment]
@stephankeller no offense taken we're all doing our best

**Comment by atchuthan** [comment]
@pedrobaeza for bom_stock module link in this issue, please point to https://github.com/OCA/stock-logistics-warehouse/tree/9.0/stock_available_mrp as this module has similar functionality.

**Comment by OSguard** [comment]
purchase_bom_split
bom_split
sale_bom_split

all three are not need for v8+ as the odoo core cover this features already

**Comment by pedrobaeza** [comment]
Can you please make the corresponding PRs?
